#!/system/bin/sh

MODPATH=.

# import functions
. $MODPATH/common.sh

FRIDA_SERVER_FILENAME=$(get_config FRIDA_SERVER_FILENAME shiny-egg)



function script_usage() {
    printf "Usage: mafrida [--set <frida-version> | -g | kill | start | status]\n"
    printf "  --set <version>               Set and install the specified Frida version (e.g., 16.1.4)\n"
    printf "  -g                            Show the currently set Frida version\n"
    printf "  -p, --port <port>             Set server port, default: 27042\n"
    printf "  -i, --ip <ip>                 Set the server's listening IP, default: 127.0.0.1\n"
    printf "  -n, --server-filename <name>  server filename, default: shiny-egg\n"    
    printf "  download                      Download the frida-server binary for the set version\n"
    printf "  kill                          Force kill any running frida-server instance\n"
    printf "  start                         Start frida-server using the set version\n"
    printf "  status                        Check if frida-server is currently running\n"
    printf "  enable                        Enable frida-server to auto-start on boot\n"
    printf "  disable                       Disable frida-server from auto-starting on boot\n"
}




if [[ $# -lt 3 ]]; then

    # set frida server version
    if [[ $1 == "--set" ]]; then

        if [[ $# -ne 2 ]]; then
            echo "- must specify the version"
            exit 1
        else
            echo "- setting frida server version to $2"
            set_config FRIDA_VERSION $2
        fi;

    # get frida server version
    elif [[ $1 == "-g" ]]; then

        echo "- current Frida server version: $(get_config FRIDA_VERSION null)"
    
    # set custom server port
    elif [[ $1 == "-p" || $1 == "--port" ]]; then

        echo "- setting port to $2"
        set_config SERVER_PORT $2

    # set custom listening ip
    elif [[ $1 == "-i" || $1 == "--ip" ]]; then

        echo "- setting ip to $2"
        set_config SERVER_IP $2

    # set custom filename for frida server
    elif [[ $1 == "-n" || $1 == "--server-filename" ]]; then

        if pgrep -f "$FRIDA_SERVER_FILENAME" > /dev/null; then
            echo "- Frida server is running. Please kill the process before changing the filename."
            exit 1;
        else
            echo "- setting server filename to '$2'"
            rename_server_filename $2
            set_config FRIDA_SERVER_FILENAME $2
        fi;

    elif [[ $1 == "download" ]]; then
        if pgrep -f "$FRIDA_SERVER_FILENAME" > /dev/null; then
            echo "- Frida server is already running. Please kill the process first!"
            exit 1
        else
            init_download_dir >/dev/null 2>&1
            echo "- Downloading..."
            init_frida_server
            echo "- Done."
        fi;
    
    # kill server if running
    elif [[ $1 == "kill" ]]; then
        if pgrep -f "$FRIDA_SERVER_FILENAME" > /dev/null; then
            kill -9 $(pidof $FRIDA_SERVER_FILENAME)
            echo "- server killed!"
        
        else
            echo "- server is not running."
        fi;
    
    # start frida server
    elif [[ $1 == "start" ]]; then
        if pgrep -f "$FRIDA_SERVER_FILENAME" > /dev/null; then
            echo "- server is already running."
        else
            port=$(get_config SERVER_PORT 27042)
            ip=$(get_config SERVER_IP 127.0.0.1)
            nohup "$MODPATH/files/$FRIDA_SERVER_FILENAME" --listen "$ip:$port" > "$MODPATH/nohup.out" 2>&1 &
            echo "- server started!, happy hacking :)"
        fi;
    
    # check if server is running
    elif [[ $1 == "status" ]]; then
        if pgrep -f "$FRIDA_SERVER_FILENAME" > /dev/null; then
            echo "- server is running on $(get_config SERVER_IP 127.0.0.1):$(get_config SERVER_PORT 0) :)"
        else
            echo "- server is not running :("
        fi;
    
    # enable frida server to start on boot
    elif [[ $1 == "enable" ]]; then

        set_config START_ON_BOOT true

    # disable frida server on boot    
    elif [[ $1 == "disable" ]]; then

        set_config START_ON_BOOT false

    else
        script_usage

    fi;
else
    script_usage
fi;
